### ISSUE TITLE
Address screen

### ISSUE THREAD

**Issue by LukeBMorrow** [Group-Two-Seven/MS3#12]
Add a screen for address. We can worry about adding the map later if we have time.

**Comment by QuocViNguyen** [comment]
Is this address page close to the Figma proto?

**Comment by LukeBMorrow** [comment]
Yes. Get the form, button, and text down.
Don't worry about making it beautiful yet, we can do that step later.

**Comment by QuocViNguyen** [comment]
This might be a stupid question, but should I make it in a separate HTML file?

**Comment by LukeBMorrow** [comment]
Unfortuantely, I cant make that work without some workarounds in the browser. 
So write the new HTML in the main_content section in its own div id="address_tab" section.
