### ISSUE TITLE
Add mock pictures to file repo

### ISSUE THREAD

**Issue by LukeBMorrow** [Group-Two-Seven/MS3#8]
Just like it sounds. Need images for use in menu items, restaurants, categories, and news items.

**Comment by QuocViNguyen** [comment]
I got it. Do you need a specific ratio or # of pics?

**Comment by LukeBMorrow** [comment]
probably just the pictures used in the Figma. That is, unless someone has a better idea

**Comment by LukeBMorrow** [comment]
More specifically, right now we need food images for the menu and cart screen. Ideally the photos all share an aspect ratio

**Comment by LukeBMorrow** [comment]
All we need now are images for food items on the menu
